"""create chunks table

Revision ID: c88ca44e1bb9
Revises: 0001
Create Date: 2026-05-17 00:13:50.646497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88ca44e1bb9'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    #op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.drop_constraint(op.f('documents_content_hash_key'), 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=True)
    op.execute("ALTER TABLE chunks ADD COLUMN embedding vector(384)")
    op.execute("""
      CREATE INDEX ix_chunks_embedding_hnsw
      ON chunks
      USING hnsw (embedding vector_cosine_ops)
  """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_unique_constraint(op.f('documents_content_hash_key'), 'documents', ['content_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
